/lslidar_driver_node:
  ros__parameters: 
    frame_id: laser                                         #激光坐标
    group_ip: 224.1.1.2
    add_multicast: false 
    device_ip: 192.168.1.200                                #雷达目的ip
    device_ip_difop: 192.168.1.102                          #雷达源IP
    msop_port: 2368                                         #雷达目的端口号
    difop_port: 2369                                        #雷达源端口号
    lidar_name: M10_P                                         #雷达选择:M10 M10_P M10_PLUS M10_GPS N10
    ceil_increase: -1                                        #Lsm10*时改值应设置为-1
    angle_disable_min: 0.0                                  #单角度裁剪开始值
    angle_disable_max: 0.0                                  #单角度裁剪结束值
    truncated_mode_: 0                                      #多角度裁剪开关：值为0时表示不使用多角度裁剪，默认为0
                                                            #值为1表示使用多角度裁剪，同时angle_disable_min与angle_disable_max设为 0，角度值在/lslidar_driver.cc中修改
    min_range: 0.0                                          #雷达接收距离最小值
    max_range: 200.0                                        #雷达接收距离最大值
    use_gps_ts: false                                       #雷达是否使用GPS授时
    scan_topic: /scan                                       #设置激光数据topic名称
    interface_selection: serial                             #接口选择:net 为网口,serial 为串口。
    serial_port_: /dev/wheeltec_laser                              #串口连接时的串口号
    high_reflection: false                                  #M10_P雷达需填写该值,若不确定，请联系技术支持。
    compensation: false				                              #M10系列是否使用角度补偿功能
    pubScan: true                                           #是否发布scan话题
    pubPointCloud2: false                                    #是否发布pointcloud2话题
    pointcloud_topic: /lslidar_point_cloud                  #设置激光数据topic名称
#    pcap: /home/ls/1.pcap                                  #雷达是否使用pcap包读取功能
#    in_file_name: /home/ls/1.txt                           #雷达是否使用txt文件读取功能